import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/417yjF+Z5zL.jpg",
    name: "Deep Work",
    author: "Cal Newport",
    discountedPrice: 219,
    price: 399,
    isBestSeller: false,
    category: "Self Help",
    rating: 2,
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/jpu324w0/book/0/9/0/believe-in-yourself-original-imafbzz2h7yfg5zz.jpeg?q=70",
    name: "Believe In Yourself",
    author: "Joseph",
    discountedPrice: 250,
    price: 1200,
    isBestSeller: true,
    category: "Self Help",
    rating: 4,
  },

  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kokdci80/regionalbooks/t/x/c/zero-to-one-original-imag2zzngtfasecu.jpeg?q=70",
    name: "Zero To One",
    author: "Peter Thiel",
    discountedPrice: 50,
    price: 500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 2,
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/x/s/w/atomic-habits-original-imag7kbzg2fu8rjv.jpeg?q=70",
    name: "Atomic Habits",
    author: "James Clear",
    discountedPrice: 390,
    price: 790,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.8,
  },

  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kufuikw0/book/0/6/q/ikigai-original-imag7kc7q5ugy2km.jpeg?q=70",
    name: "IKIGAI",
    author: "Hector Garcia",
    discountedPrice: 600,
    price: 1500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4,
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kgwld3k0/book/1/9/4/rich-dad-poor-dad-original-imafxf885pytvycy.jpeg?q=70",
    name: "Rich Dad Poor Dad",
    author: "Robert Kiyoski",
    discountedPrice: 350,
    price: 500,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 1,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/91B7iSLeVkL._AC_UF1000,1000_QL80_.jpg",
    name: "Kill Joy",
    author: "Holly Jackson",
    discountedPrice: 119,
    price: 249,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 3,
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/ki96c280-0/book/3/p/n/one-indian-girl-original-imafy2zrymfbtygz.jpeg?q=70",
    name: "One Indian Girl",
    author: "Chetan Bhagat",
    discountedPrice: 157,
    price: 195,
    isBestSeller: false,
    category: "Fiction",
    rating: 3,
  },
  {
    _id: uuid(),
    img: "https://www.readandcobooks.co.uk/wp-content/uploads/bleak-house-dickens-9781528716932-cover.jpg",
    name: "Bleak House",
    author: "Charles Dickens",
    discountedPrice: 163,
    price: 205,
    isBestSeller: true,
    category: "Fiction",
    rating: 2.5,
  },
  {
    _id: uuid(),
    img: "https://rukminim1.flixcart.com/image/612/612/kwpam4w0/book/r/a/r/-original-imag9bv6bzstsjgk.jpeg?q=70",
    name: "Fair Play",
    author: "Eve Rodsky",
    discountedPrice: 699,
    price: 999,
    isBestSeller: false,
    category: "Self Help",
    rating: 4,
  },
  {
    _id: uuid(),
    img: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781647229733/the-journey-9781647229733_hr.jpg",
    name: "The Journey",
    author: "James Norbury",
    discountedPrice: 399,
    price: 699,
    isBestSeller: false,
    category: "Self Help",
    rating: 3.5,
  },
  {
    _id: uuid(),
    img: "https://miro.medium.com/v2/resize:fit:1400/1*R4_ukD-ZC92gIbN9kABZng.jpeg",
    name: "Can't hurt me",
    author: "David Goggins",
    discountedPrice: 243,
    price: 349,
    isBestSeller: true,
    category: "Non Fiction",
    rating: 1,
  },
  {
    _id: uuid(),
    img: "https://media.shortform.com/covers/png/the-power-of-habit-cover.png",
    name: "The Power of Habit",
    author: "Charles Duhigg",
    discountedPrice: 320,
    price: 520,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.5,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41yu2qXhXXL.jpg",
    name: "Sapiens",
    author: "Yuval Noah Harari",
    discountedPrice: 400,
    price: 600,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.7,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51Z0nLAfLmL.jpg",
    name: "The Alchemist",
    author: "Paulo Coelho",
    discountedPrice: 250,
    price: 350,
    isBestSeller: false,
    category: "Fiction",
    rating: 4.3,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71wAI5TwNsL._AC_UF1000,1000_QL80_.jpg",
    name: "Principles",
    author: "Ray Dalio",
    discountedPrice: 300,
    price: 500,
    isBestSeller: true,
    category: "Self Help",
    rating: 4.1,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81dkqO5LAQL._AC_UF1000,1000_QL80_.jpg",
    name: "The Silent Patient",
    author: "Alex Michaelides",
    discountedPrice: 280,
    price: 480,
    isBestSeller: false,
    category: "Fiction",
    rating: 4.2,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/812wVvcrAjL._AC_UF1000,1000_QL80_.jpg",
    name: "Educated",
    author: "Tara Westover",
    discountedPrice: 310,
    price: 510,
    isBestSeller: false,
    category: "Non Fiction",
    rating: 4.4,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61Av4S46owL._AC_UF1000,1000_QL80_.jpg",
    name: "The 5 AM Club",
    author: "Robin Sharma",
    discountedPrice: 270,
    price: 470,
    isBestSeller: true,
    category: "Self Help",
    rating: 3.9,
  },
  {
    _id: uuid(),
    img: "https://d2pyicwmjx3wii.cloudfront.net/s/607fe93d7eafcac1f2c73ea4/6385ac83f3a1d2280ca6a0e2/webp/513tu2ghgrl-_sx424_bo1-204-203-200_-640x640.jpg",
    name: "Great Expectations",
    author: "Charles Dickens",
    discountedPrice: 260,
    price: 460,
    isBestSeller: true,
    category: "Fiction",
    rating: 5.0,
  }
];
